name: Fetch Weather Data

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:  # REQUIRED for manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Run fetch script
        run: node fetch-data.js

      - name: Commit and push data.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/data.json
          git commit -m "Update data.json"
          git push
